# List of plugins
set -g @plugin 'catppuccin/tmux#v2.3.0'
set -g @catppuccin_flavor 'mocha'

set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'

set -g base-index 1
setw -g pane-base-index 1
set -g mouse on
set -g default-terminal "screen-256color"
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -s escape-time 0
set -g renumber-windows on


# Pane
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# --- Status Bar Settings ---
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=white bg=default'

set -g status-left '#[fg=black,bg=blue,bold]  #S #[fg=blue,bg=default] '
set -g status-left-length 30

set -g status-right '#[fg=brightblack,bg=default]#[fg=white,bg=brightblack] 󰃭 %Y-%m-%d #[fg=blue,bg=brightblack]#[fg=black,bg=blue,bold] 󱑒 %H:%M '
set -g status-right-length 50

setw -g window-status-current-format '#[fg=blue,bg=default] #[fg=black,bg=blue,bold]#I:#W#F#[fg=blue,bg=default]'

setw -g window-status-format '#[fg=gray,bg=default]  #I:#W  '

set -g pane-border-style 'fg=brightblack'
set -g pane-active-border-style 'fg=blue'

# # vim key-binding
# setw -g mode-keys vi
# bind -T copy-mode-vi 'v' send -X begin-selection
# bind -T copy-mode-vi 'y' send -X copy-pipe-and-cancel "pbcopy"

# bind-key -T copy-mode-vi 'h' send -X cursor-left
# bind-key -T copy-mode-vi 'j' send -X cursor-down
# bind-key -T copy-mode-vi 'k' send -X cursor-up
# bind-key -T copy-mode-vi 'l' send -X cursor-right

set-option -g default-shell $SHELL
